### ISSUE TITLE
Cannot launch the program

### ISSUE THREAD

**Issue by AitorManteca** [FowlerLab/Enrich2#10]
Hello,

I cannot launch the program with the example that you have in the repository. Apprently I have installed, Anaconda and all the packages but when I try to run it, the following errors appear:

AI-MAC-6:Enrich2-Example-master Aitor$ enrich_cmd
Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pandas 0.20.3 (/Users/user/anaconda3/lib/python3.6/site-packages), Requirement.parse('pandas<0.20'), {'Enrich2'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/anaconda3/bin/enrich_cmd", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pandas<0.20' distribution was not found and is required by Enrich2

Do you know what the problem could be? I am an experimentalist and my knowledge of phyton is very limited.

Thank you very much.

Aitor

**Comment by afrubin** [comment]
Thanks for your report. It looks like you are trying to run Enrich2 from Python 3.6, but only Python 2.7 is supported. Your current installation of Anaconda will work fine, but you need to create a Python 2.7 environment for Enrich2 to run in.

To set up a new environment for Enrich2, download the `enrich2_env.yml` environment file from the [Enrich2 documentation](http://enrich2.readthedocs.io/en/latest/installation.html#installation-and-example-dataset). The instructions for creating a conda environment from a file are in the [conda documentation](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file).

Once you have created and activated the new Enrich2 environment, continue with installation as normal. You will need to activate the environment whenever you want to launch Enrich2, but it will otherwise work normally.

Let me know if this gets you started!

**Comment by AitorManteca** [comment]
Hi again!

It worked both with commands and with the GUI!! Yay :)

Many many thanks Alan!!
