### ISSUE TITLE
Error: too few arguments

### ISSUE THREAD

**Issue by samantneha** [FowlerLab/Enrich2#29]
Hello,
I am attempting to use Enrich for variant counting and I am getting the following error:
usage: Enrich2 [-h] [--version] [--log FILE] [--no-plots] [--no-tsv]
               [--recalculate] [--component-outliers] [--output-dir DIR]
               [--sfmap-aa-file FILE]
               config {WLS,ratios,counts,OLS,simple} {wt,complete,full}
Enrich2: error: too few arguments

I have previously used this same configuration successfully and I do not know how to resolve this issue. Please help.

Thanks.

**Comment by afrubin** [comment]
You need to provide the configuration file as well as the scoring and normalization methods on the command line. 

For example:
`enrich_cmd my_config_file.json WLS wt`

You can see all the choices in the usage string that you posted. Additional details about each method can be found in the documentation.

**Comment by samantneha** [comment]
Hi Alan,

Thanks for the suggestions, I tried it, and this is what I am getting. I also tried to re-install Enrich2 version 1.2.1, and I ususally use thr GUI which is giving me an error: Not responding 
This is how I setup the GUI
![IMG_3846](https://user-images.githubusercontent.com/49453104/71566175-5a29e980-2a83-11ea-8c47-9432c77a03c5.jpg)
Thanks

**Comment by afrubin** [comment]
The previous comment was to help you use the command-line interface for the program. I'm not sure how to reply since you haven't provided any additional output.

I don't have enough information to help you with the GUI from that picture, sorry. You mentioned that you used this configuration successfully before, so perhaps focus on what's changed since then?

**Comment by samantneha** [comment]
I am extremely sorry, I forgot to paste the error code, through the command line interface
Please find it below. 
C:\Users\samantn>enrich_cmd configuration1 ratios wt
2019-12-29 20:55:25,326 [enrich_cmd] Detected a Selection config file
2019-12-29 20:55:25,655 [TEST] Creating new HDF5 data store "C:/Users/samantn/Desktop/MA_CA_SEQ2019\TEST_sel.h5"
2019-12-29 20:55:25,733 [sample1] Creating new HDF5 data store "C:/Users/samantn/Desktop/MA_CA_SEQ2019\sample1_lib.h5"
2019-12-29 20:55:25,733 [sample5] Creating new HDF5 data store "C:/Users/samantn/Desktop/MA_CA_SEQ2019\sample5_lib.h5"
2019-12-29 20:55:25,733 [TEST] Counting for each time point (variants)
2019-12-29 20:55:25,733 [sample1] Counting variants
Traceback (most recent call last):
  File "C:\Users\samantn\AppData\Local\Continuum\anaconda2\Scripts\enrich_cmd-script.py", line 11, in <module>
    load_entry_point('Enrich2==1.2.1', 'console_scripts', 'enrich_cmd')()
  File "build\bdist.win-amd64\egg\enrich2\main.py", line 230, in main_cmd
  File "build\bdist.win-amd64\egg\enrich2\selection.py", line 386, in calculate
  File "build\bdist.win-amd64\egg\enrich2\selection.py", line 285, in merge_counts_unfiltered
  File "build\bdist.win-amd64\egg\enrich2\basic.py", line 167, in calculate
  File "build\bdist.win-amd64\egg\enrich2\basic.py", line 147, in counts_from_reads
  File "build\bdist.win-amd64\egg\enrich2\seqlib.py", line 200, in save_counts
ValueError: Failed to count variants [sample1]
Closing remaining open files:C:/Users/samantn/Desktop/MA_CA_SEQ2019\TEST_sel.h5...doneC:/Users/samantn/Desktop/MA_CA_SEQ2019\sample5_lib.h5...doneC:/Users/samantn/Desktop/MA_CA_SEQ2019\sample1_lib.h5...done

For the GUI, I am using this setup above which is exactly the same as before, I use the same input file, I changed to output folder, the Triming and Variant options are same as before. The output was a H5 file and 4 tsv file as below:
![Untitled](https://user-images.githubusercontent.com/49453104/71567601-5485d100-2a8e-11ea-9702-36d489d73000.png)

If I run the same settings now the error I get is Not Responding, it creats 3 H5 files of 1Kb. 
Thank you for your help.

**Comment by afrubin** [comment]
`ValueError: Failed to count variants [sample1]` is the error returned when there are no counts, for example because all of the reads were filtered out. I am not sure why it would have worked before and now fail with the same settings and same input files.

I suggest double-checking your filtering and trimming settings by inspecting the fastq file, and also make sure that the file path in the configuration is pointing to a fastq file with the right data in it.
