### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Saro86** [FowlerLab/Enrich2#32]
Dear all,

Using the Enrich2 software package for the analysis of my pre-processed fastq files I run sometimes into an "IndexError: string index out of range". 

```
2020-03-27 18:01:19,697 [enrich_cmd] Detected a BasicSeqLib config file
2020-03-27 18:01:19,697 [test] Creating new HDF5 data store "/home/oooo/Desktop/out/test_lib.h5"
2020-03-27 18:01:19,713 [test] Counting variants
Traceback (most recent call last):
  File "/home/oooo/anaconda3/envs/enrich2/bin/enrich_cmd", line 11, in <module>
    load_entry_point('Enrich2==1.2.1', 'console_scripts', 'enrich_cmd')()
  File "build/bdist.linux-x86_64/egg/enrich2/main.py", line 230, in main_cmd
  File "build/bdist.linux-x86_64/egg/enrich2/basic.py", line 167, in calculate
  File "build/bdist.linux-x86_64/egg/enrich2/basic.py", line 136, in counts_from_reads
  File "build/bdist.linux-x86_64/egg/enrich2/variant.py", line 402, in count_variant
IndexError: string index out of range
Closing remaining open `files:/home/oooo/Desktop/out/test_lib.h5...done `
```

I identified the sequences that caused the error in some occasion but I could not see anything in particular to be fixed. Simply they look exactly like all the other sequences in the fastq file. 

Have you had some of these issues before or do you have some idea to try to fix it?

Thanks in advance,
Rosario

**Comment by afrubin** [comment]
Without some sample data it's hard to figure out what's going on here. Can you post some of the FASTQ records that are fine and the ones that are failing?

**Comment by Saro86** [comment]
Hi, attached are two  files. 1.fastq is the one working fine while the 144401.fastq is the one with the error.

[fastq files.tar.gz](https://github.com/FowlerLab/Enrich2/files/4443269/fastq.files.tar.gz)

**Here is what I get with the 144401.fastq**
$ enrich_cmd test.json ratios wt
2020-04-07 11:12:08,295 [enrich_cmd] Detected a BasicSeqLib config file
2020-04-07 11:12:08,296 [test] Creating new HDF5 data store "/home/saro/Desktop/out/test_lib.h5"
2020-04-07 11:12:08,311 [test] Counting variants
Traceback (most recent call last):
  File "/home/oooo/anaconda3/envs/enrich2/bin/enrich_cmd", line 11, in <module>
    load_entry_point('Enrich2==1.2.1', 'console_scripts', 'enrich_cmd')()
  File "build/bdist.linux-x86_64/egg/enrich2/main.py", line 230, in main_cmd
  File "build/bdist.linux-x86_64/egg/enrich2/basic.py", line 167, in calculate
  File "build/bdist.linux-x86_64/egg/enrich2/basic.py", line 136, in counts_from_reads
  File "build/bdist.linux-x86_64/egg/enrich2/variant.py", line 402, in count_variant
IndexError: string index out of range
Closing remaining open files:/home/oooo/Desktop/out/test_lib.h5...done

**Here is what I get with the 1.fastq**
$ enrich_cmd test.json ratios wt
2020-04-07 11:15:07,921 [enrich_cmd] Detected a BasicSeqLib config file
2020-04-07 11:15:07,921 [test] Found existing HDF5 data store "/home/saro/Desktop/out/test_lib.h5"
2020-04-07 11:15:07,938 [test] Counting variants
2020-04-07 11:20:21,280 [test] Counted 100 variants (73 unique)
2020-04-07 11:20:21,295 [test] Aligned 73 variants
2020-04-07 11:20:21,295 [test] Removed 0 total variants with excess mutations
2020-04-07 11:20:21,313 [test] Converting raw variants counts to main counts
2020-04-07 11:20:21,336 [test] Counted 100 variants (73 unique) after query
2020-04-07 11:20:21,343 [test] Counting synonymous variants
2020-04-07 11:20:21,350 [test] Counted 100 synonymous (70 unique)
2020-04-07 11:20:21,367 [test] Creating plots
2020-04-07 11:20:22,418 [test] Creating plots
2020-04-07 11:20:23,274 [test] Generating tab-separated output files
`
Thanks,
Rosario

**Comment by tboonf** [comment]
Hi @Saro86 I have encountered the same issue of IndexError: string index out of range. Just wondering if you have figured out what might have caused the issue. Thanks!

**Comment by Saro86** [comment]
Hi @tboonf , the way it worked for me was to trim the sequences before running the analysis with Enrich2 at exactly the size of the input sequence. In this last case the error did not show up.

**Comment by tboonf** [comment]
Thanks @Saro86 I trimmed down all the raw reads to a fixed size, and that appears to have solved the problem, i.e. at least Enrich2 is now able to "count variant". 

@afrubin 
Despite that, I still received this error message: "Failed to use wild type log ratio method, wild type sequence not present [rep1]". I have triple checked that wild type sequence was keyed in properly. This error only appears when choosing the option "wild type"
But when choosing the option library size (all reads), i received this error message instead: "[enrich2.dataframe] Wild type score not measured, will be missing in plots" and also "Calculations completed, but plotting failed: unrecogznied HGVS string"

All help is very much appreciated.
