### ISSUE TITLE
IndexError: Failed to calculate overlap

### ISSUE THREAD

**Issue by ijhoskins** [FowlerLab/Enrich2#53]
Hello @afrubin 

I experienced the following error running Enrich2 overlap count mode:
```
2021-12-02 17:39:35,750 [enrich2.main] Detected a OverlapSeqLib config file
2021-12-02 17:39:35,751 [enrich2.wildtype.<class 'enrich2.wildtype.WildTypeSequence'>] Ignoring reference offset for protein changes (not a multiple of three)
2021-12-02 17:39:35,751 [enrich2.overlap.OverlapSeqLib - CBS_pAG415GAL_tile6_sim] Creating new HDF5 data store "/scratch/users/ihoskins/variant_call_compare/enrich/CBS_pAG415GAL_tile6_sim_lib.h5"
2021-12-02 17:39:35,766 [numexpr.utils] Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2021-12-02 17:39:35,766 [numexpr.utils] Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2021-12-02 17:39:35,767 [numexpr.utils] NumExpr defaulting to 8 threads.
2021-12-02 17:39:35,774 [enrich2.overlap.OverlapSeqLib - CBS_pAG415GAL_tile6_sim] Counting variants
Traceback (most recent call last):
  File "/home/ihoskins/miniconda3/envs/enrich2/bin/enrich_cmd", line 11, in <module>
    load_entry_point('Enrich2==1.3.1', 'console_scripts', 'enrich_cmd')()
  File "build/bdist.linux-x86_64/egg/enrich2/main.py", line 228, in main_cmd
  File "build/bdist.linux-x86_64/egg/enrich2/overlap.py", line 323, in calculate
  File "build/bdist.linux-x86_64/egg/enrich2/overlap.py", line 274, in counts_from_reads
  File "build/bdist.linux-x86_64/egg/enrich2/overlap.py", line 231, in merge_reads
IndexError: Failed to calculate overlap (a=152, len(a)=152, b=151, len(b)=152) [CBS_pAG415GAL_tile6_sim]
Closing remaining open files:/scratch/users/ihoskins/variant_call_compare/enrich/CBS_pAG415GAL_tile6_sim_lib.h5...done
```

Here is my config:
```
{
  "fastq": {
    "filters": {
      "avg quality": 20, 
      "max N": 10
    }, 
    "forward reads": "/Users/ianhoskins/data_staging/Methods_paper/variant_call_compare/enrich2/CBS_pAG415GAL_tile6_sim.R1.fq.gz", 
    "reverse reads": "/Users/ianhoskins/data_staging/Methods_paper/variant_call_compare/enrich2/CBS_pAG415GAL_tile6_sim.R2.fq.gz"
  }, 
  "name": "test", 
  "output directory": "/Users/ianhoskins/data_staging/Methods_paper/variant_call_compare/enrich2", 
  "overlap": {
    "forward start": 1, 
    "length": 153, 
    "max mismatches": 10, 
    "reverse start": 1, 
    "trim": false
  }, 
  "report filtered reads": false, 
  "timepoint": 0, 
  "variants": {
    "max mutations": 3, 
    "min count": 2, 
    "use aligner": true, 
    "wild type": {
      "coding": true, 
      "reference offset": 715, 
      "sequence": "GACGTGCTGCGGGCACTGGGGGCTGAGATTGTGAGGACGCCCACCAATGCCAGGTTCGACTCCCCGGAGTCACACGTGGGGGTGGCCTGGCGGCTGAAGAACGAAATCCCCAATTCTCACATCCTAGACCAGTACCGCAACGCCAGCAACCCC"
    }
  }
}
```

I get the same error when "use aligner" is true or false. I suspect this is because (some of) my input reads have InDels in them, despite all reads starting and ending flush with the reference sequence. Is this expected?

Also, my offset is not a multiple of three because the first base of the coding region is not a multiple of three starting from the first base of the full transcript reference.

Do you think this latter issue is causing the problem or the fact that a small fraction of the input reads do not match the reference length? I could always filter out reads with InDels if need be to meet the length requirement.

Thanks!

**Comment by afrubin** [comment]
Thanks for using Enrich2!

> Do you think this latter issue is causing the problem or the fact that a small fraction of the input reads do not match the reference length? I could always filter out reads with InDels if need be to meet the length requirement.

Without seeing the reads it's hard to tell, but this is likely the case. One option is to filter out reads based on length as you said.

Another option is to use another program like [FLASH2](https://github.com/dstreett/FLASH2) to merge your read pairs, and then send the resulting file to Enrich2 as a BasicSeqLib. Enrich2's overlap mode is a quite primitive and inflexible by comparison, so this sometimes gives better results.

**Comment by ijhoskins** [comment]
Hi @afrubin, thanks for your response. I was able to bypass the error by filtering out the reads with InDels. I have encountered some other issues I will open issues for.
