### ISSUE TITLE
Variant DNA sequence contains unexpected characters 

### ISSUE THREAD

**Issue by rmenafra** [FowlerLab/Enrich2#66]
I'm using enrich2 with some PacBio fastq sequences (that I trimmed to a fixed length).
I get the error below:

2024-05-30 16:37:19,882 [enrich2.basic.BasicSeqLib - Library2_check] Counting variants
Traceback (most recent call last):
  File "/miniconda3/envs/enrich2/bin/enrich_cmd", line 11, in <module>
    load_entry_point('Enrich2==1.3.1', 'console_scripts', 'enrich_cmd')()
  File "build/bdist.linux-x86_64/egg/enrich2/main.py", line 228, in main_cmd
  File "build/bdist.linux-x86_64/egg/enrich2/basic.py", line 155, in calculate
  File "build/bdist.linux-x86_64/egg/enrich2/basic.py", line 123, in counts_from_reads
  File "build/bdist.linux-x86_64/egg/enrich2/variant.py", line 346, in count_variant
ValueError: Variant DNA sequence contains unexpected characters [Library2_check]

I cannot understand which character is creating the problem, I have used this tool in the past with Illumina sequences without any problem.
I also tried a random subselection of the PacBio reads and the run completed successfully, therefore it should be some character not always present. Is there a way to test what's causing the issue?
Thanks
Roberta

**Comment by rmenafra** [comment]
Issue solved
